### ISSUE TITLE
 No module named 'matching.games'; 'matching' is not a package

### ISSUE THREAD

**Issue by zadeoglu** [daffidwilde/matching#176]
Hello, I am trying to use the exact same code in the documentation. I installed 1.4.3 version over pip. 

from matching.games import StableMarriage
prompts the error 
 No module named 'matching.games'; 'matching' is not a package
 
 Tried also,
 import matching
from matching.games import StableMarriage
got the same. Is the names changed somehow? I am just trying to run the code identical to the documentation. 

https://daffidwilde.github.io/matching/docs/tutorials/stable_marriage.html

**Comment by daffidwilde** [comment]
Hi @zadeoglu :wave:

If there was something wrong with the package, it would have cropped up during development since _matching_ is doc-tested and the tutorials serve as integration tests. To make sure, I've just made a fresh install of the package on my other half's machine with Python 3.12 and cannot replicate this issue.

Are you sure you've installed the package correctly in whatever environment you're using?

I'm keen to get you up and running :smile:

**Comment by zadeoglu** [comment]
The issue was because I named my file "matching.py" :facepalm:

**Comment by daffidwilde** [comment]
Ah, a sneaky issue! Glad you've resolved it. Have a good one 👍🏼
