### ISSUE TITLE
`hospital_resident` performance

### ISSUE THREAD

**Issue by justinrporter** [daffidwilde/matching#26]
Hello there!

I was trying to use your package on a moderately-sized dataset (thousands of applicants and hundreds of programs in `hospital_resident`) and found that it was a bit slow for my needs. Digging in a bit more, I found that it's scaling roughly cubically, although the algorithm ought to be quadratic (at least [according to wikipedia](https://en.wikipedia.org/wiki/Stable_marriage_problem#Solution)):

![perf](https://user-images.githubusercontent.com/3531723/48298274-5a7eb400-e480-11e8-8d4d-33fbfe902365.png)

where the x-axis is the number of applicants (there are sqrt(n) programs with capacity sqrt(n) each) and the y-axis is seconds.

So, I profiled the function and found the following timings:

```
Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
     1                                           def hospital_resident(hospital_prefs, resident_prefs, capacities):
     2                                               """ Provide a stable, resident-optimal matching for the given instance of
     3                                               HR using the algorithm set out in [Dubins, Freeman 1981]. """
     4                                           
     5         1    2451690.0 2451690.0      8.4     check_inputs(hospital_prefs, resident_prefs)
     6                                           
     7         1         31.0     31.0      0.0      matching = {hospital: [] for hospital in hospital_prefs}
     8         1       9221.0   9221.0      0.0      free_residents = algorithms.get_free_residents(resident_prefs, matching)
     9     22348      17113.0      0.8      0.1      while free_residents:
    10     22347      13612.0      0.6      0.0          resident = free_residents[0]
    11     22347      14599.0      0.7      0.1          hospital = resident_prefs[resident][0]
    12     22347      27357.0      1.2      0.1          matching[hospital].append(resident)
    13                                           
    14     22347      29692.0      1.3      0.1          if len(matching[hospital]) > capacities[hospital]:
    15     21987    8139534.0    370.2     27.9              worst = get_worst_idx(hospital, hospital_prefs, matching)
    16     21987      20613.0      0.9      0.1              resident = hospital_prefs[hospital][worst]
    17     21987      24224.0      1.1      0.1              matching[hospital].remove(resident)
    18                                           
    19     22347      26289.0      1.2      0.1          if len(matching[hospital]) == capacities[hospital]:
    20     22107    7147253.0    323.3     24.5              worst =get_worst_idx(hospital, hospital_prefs, matching)
    21     22107      29695.0      1.3      0.1              successors = hospital_prefs[hospital][worst + 1:]
    22                                           
    23     22107      12046.0      0.5      0.0              if successors:
    24     72238      42346.0      0.6      0.1                  for resident in successors:
    25     50220     444998.0      8.9      1.5                      hospital_prefs[hospital].remove(resident)
    26     50220      45625.0      0.9      0.2                      if hospital in resident_prefs[resident]:
    27     50220      51022.0      1.0      0.2                          resident_prefs[resident].remove(hospital)
    28                                           
    29     22347   10572802.0    473.1     36.3          free_residents = get_free_residents(resident_prefs, matching)
    30                                           
    31       121         78.0      0.6      0.0      for hospital, matches in matching.items():
    32       120       7329.0     61.1      0.0          sorted_matches = sorted(matches, key=hospital_prefs[hospital].index)
    33       120        124.0      1.0      0.0          matching[hospital] = sorted_matches
    34                                           
    35         1          0.0      0.0      0.0      return matching
```

This was with an 120 programs with capacity 3 and 600 applicants (total runtime 29.1 sec).

A few things that you might be able to improve off the bat:

1. Correct me if I'm wrong here, but in `get_worst_idx` (roughly 50% of the runtime), could you get away with not iterating through every resident in `hospital_prefs`; instead just through every resident that's presently matched at the hospital? Like so:

```python
def get_worst_idx(hospital, hospital_prefs, matching):
    """Find the index of the worst resident currently assigned to `hospital`
    according to their preferences."""

    idxs = []
    
    for resident in matching[hospital]:
        idxs.append(hospital_prefs[hospital].index(resident))
    
    return max(idxs)
```

2. My hunch is that the repeated use of `get_free_residents` is what's creating the cubic runtime. Instead of having a function that recalculates it, could you initialize a set that contains all residents at the outset, and then removes them one by one as they match?

And, a final general question: can't you just simulate hospitals with capacity >1 in the traditional Gale-Shapley by creating _n_ reviewers with identical preferences, where _n_ is the hospital's capacity? Then you could just pipe it into your Gale-Shapley implementation, get the result back, and reshape it to look like it should (and save yourself the trouble of maintaining/optimizing two different core algorithms).

Thanks for sharing your code!

Cheers!

**Comment by daffidwilde** [comment]
Hello, @justinrporter!

Thank you for such an in-depth issue, and sorry that it has taken me until the new year to reply. I've had a good, long think about everything you've included here and I agree with you.

Since the first release of this library, I have begun to implement a hospital-optimal algorithm and found that, similarly, finding `free_hospitals` takes a long time as with the `free_residents` here. A previous implementation I wrote (long before this release or even the hospital-resident algorithm) did what you suggest and kept track of which players were matched at any time using an initialised list.

However, the particular algorithm being implemented (found in [this thesis](http://theses.gla.ac.uk/64/1/2007omalleyphd.pdf) -- along with the other Gale-Shapley algorithms) seemed to require this additional component, hence its inclusion. Though there is likely another implementation (or interpretation) that maintains such a list on the fly, thus reducing the complexity of the algorithm, I can't imagine an elegant workaround for this implementation since a resident/hospital's freedom is defined by both its undersubscribed/unmatched state and the non-emptiness of its preference list.

One way to get around all of that (and some of the problems I've been having optimising these hospital-resident algorithms) is to pack in with these algorithms altogether, implement a general solver based around the original Gale-Shapley algorithm, and just manipulate the problem instances instead. That's the main thought that I've been coming back to with all this, especially after your final remark in this issue.

If that path was chosen, the first hurdle to overcome would be dealing with multiple, identical dictionary keys. Players' preferences are stored in dictionaries as object-list pairs and creating copies of hospitals, if they are defined by some mutable object (as they often are), is impossible as their entry would be overwritten with each copy. I would suggest that every instance of a game begins in the same way, by making each suitor/reviewer (resident/hospital) an instance of some base `Player` class. This class could have a series of attributes including `name`, `preferences`, `matched`, etc. and its instances would be immutable objects. Thus, multiple copies of a hospital could be included in the same dictionary. That could streamline some parts of the Gale-Shapley algorithm anyway... maybe.

I think this will take some time to do and test appropriately but I think it's a sensible next step for this library. Thank you again for your patience in my reply, and for your research and suggestions. Should you have another take on the ideas proposed here, I appreciate any and all comments you have to make.

Cheers

**Comment by reinoldus** [comment]
Hey folks,

came across the same issue today, in my analysis get_free_resident caused all the issues, especially this line: `any([resident in match for match in matching.values()]):`

I fixed it by replacting this call with a dict key lookup, which is just O(1):

```
def get_free_residents(resident_prefs, matching, matched_residents):
    """ Return a list of all residents who are currently unmatched but have a
    non-empty preference list. """
    a_list = []

    for resident in resident_prefs:
        if resident_prefs[resident] and resident not in matched_residents:#any([resident in match for match in matching.values()]):
            a_list.append(resident)

    return a_list
```
This required of course adding/appending the key when necessary:

```
def resident_hospital(resident_prefs, hospital_prefs, capacities):
    """ Provide a stable, resident-optimal matching for the given instance of
    HR using the algorithm set out in [Gale, Shapley 1962]. """

    matched_residents = {}
    matching = {hospital: [] for hospital in hospital_prefs}
    free_residents = get_free_residents(resident_prefs, matching, matched_residents)

    while free_residents:
        print(len(free_residents))
        resident = free_residents[0]
        hospital = resident_prefs[resident][0]
        matching[hospital].append(resident)
        matched_residents[resident] = ""

        if len(matching[hospital]) > capacities[hospital]:
            worst = get_worst_idx(hospital, hospital_prefs, matching)
            resident = hospital_prefs[hospital][worst]
            matching[hospital].remove(resident)
            del matched_residents[resident]

        if len(matching[hospital]) == capacities[hospital]:
            worst = get_worst_idx(hospital, hospital_prefs, matching)
            successors = hospital_prefs[hospital][worst + 1 :]

            if successors:
                for resident in successors:
                    hospital_prefs[hospital].remove(resident)
                    if hospital in resident_prefs[resident]:
                        resident_prefs[resident].remove(hospital)

            free_residents = get_free_residents(resident_prefs, matching, matched_residents)

    for hospital, matches in matching.items():
        sorted_matches = sorted(matches, key=hospital_prefs[hospital].index)
        matching[hospital] = sorted_matches

    return matching
```

Maybe not the prettiest solution, but needed a quick an dirty fix for my thesis. Hope I am not mistaking and this is causing any malfunction? Doesn't seem like it though.

**Comment by justinrporter** [comment]
>  I am going to move forward with having a `Player` class

I think this is probably the right idea long-term, although what @reinoldus proposed is more or less what I originally had in mind.

> the exact conditions in which you performed your analysis

I broke the environment I used to produce that scaling figure, but here's the relevant cell from the ipython notebook:

```python
n = np.linspace(10, 400, num=20).astype(int)
t = np.zeros_like(n, dtype=float)

for i, n_applicants in enumerate(n):
    print(i, n_applicants)
    n_programs = int(np.sqrt(n_applicants))
    n_slots = n_applicants // n_programs
    
    applicant_qual = np.random.normal(size=(n_applicants,))
    program_qual = np.random.normal(size=(n_programs,))

    applicant_rank = list(np.argsort(applicant_qual))
    program_rank = list(np.argsort(program_qual))
    
    resident_prefs = {i: list(program_rank) for i in range(len(applicant_rank))}
    program_prefs = {i: list(applicant_rank) for i in range(len(program_rank))}
    capacities = {h: n_slots for h in program_prefs.keys()}
    
    start = time.perf_counter()
    algorithms.hospital_resident(resident_prefs=resident_prefs, hospital_prefs=program_prefs, capacities=capacities)
    end = time.perf_counter()

    t[i] = end - start

plt.plot(n, t, label='Runtime')
plt.plot(n, (n/205)**3, '--', label='O$(n^3)$', c='black')
plt.legend()
```

**Comment by daffidwilde** [comment]
It's been a while since this issue was opened and I haven't been able to get the performance down to `O(n ** 2)` yet. Having said that, the most recent releases have shown a substantial improvement for larger instances of HR. Below is the analogous code to @justinrporter to show this performance:

```python
>>> import time

>>> from matching.games import HospitalResident
>>> import matplotlib.pyplot as plt
>>> import numpy as np

>>> ns = np.linspace(10, 400, 20).astype(int)
>>> ts = np.zeros_like(ns, dtype=float)

>>> for i, n_applicants in enumerate(ns):
...     np.random.seed(i)
...     n_programs = int(np.sqrt(n_applicants))
...     n_slots = n_applicants // n_programs
...     
...     applicant_qual = np.random.normal(size=(n_applicants,))
...     program_qual = np.random.normal(size=(n_programs,))
... 
...     applicant_rank = list(np.argsort(applicant_qual))
...     program_rank = list(np.argsort(program_qual))
... 
...     resident_prefs = {i: list(program_rank) for i in range(len(applicant_rank))}
...     program_prefs = {i: list(applicant_rank) for i in range(len(program_rank))}
...     capacities = {h: n_slots for h in program_prefs.keys()}
... 
...     game = HospitalResident.create_from_dictionaries(resident_prefs, program_prefs, capacities)
... 
...     start = time.perf_counter()
...     game.solve()
...     end = time.perf_counter()
... 
...     ts[i] = end - start

>>> fig, ax = plt.subplots(figsize=(8, 4), dpi=300)

>>> coefficients = np.polyfit(n, t, 3)
>>> polynomial = np.poly1d(coefficients)

>>> ax.plot(ns, ts, label='Runtime')
>>> ax.plot(ns, polynomial(ns), '--', label='O$(n^3)$', c='black')
>>> ax.legend()

>>> plt.show()
>>> print(coefficients)
[2.86185034e-09 3.39148756e-07 2.58945693e-06 1.17049796e-04]
```
![performance](https://user-images.githubusercontent.com/26261131/73088351-f9e46700-3ecb-11ea-90ec-b42eea5c84ad.png)

That's a roughly 96% decrease in times for the largest game size tested. I'm fairly happy with that so I'll be closing this issue for now.

If you wish to improve further on this, please open up a PR 👍

**Comment by justinrporter** [comment]
Looks much better! I'll write back whenever I get a chance to play around with things again. There's a tendency to focus on these asymptotic performance characteristics (I'm including myself in this), but it's important to remember that in real life our data always in fact has a finite size!
