### ISSUE TITLE
Use matching from php

### ISSUE THREAD

**Issue by reinoud1957** [daffidwilde/matching#99]
Is there an example using matching stable roommates from php  
$output = exec( ./  stable_roommates.py)   with a preference list?

**Comment by daffidwilde** [comment]
Hi there, @reinoud1957. Thanks for raising this issue but unfortunately the answer is no. Support for PHP is well beyond the scope of this library, and the purpose of `matching` is to provide a Python interface to the algorithms used for solving some matching games rather than an executable script as you desire.

I'm unsure of how you might import something from Python to PHP but I suspect your best bet is to write a script in Python that uses the `StableRoommates` class that executes as you require.

As I can't provide any further advice on this, I'll be closing the issue.
